engines:
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- test/**/*
- server/http/js/automation/buffer.js
- server/http/js/automation/require.js
- server/http/js/primus.js
- server/http/js/swfobject.js
- server/http/js/translations.js
- server/http/js/vendor/primus.js
- server/http/css/roboto.css
- server/http/js/automation/EventEmitter.min.js
- server/http/js/jquery-1.11.0.min.js
- server/http/js/jquery-ui.min.js
