language: node_js
node_js:
  - "0.12"
  - "iojs-v2.5.0"
  - "iojs-v3.0.0"
  
cache:
  directories:
    - node_modules

before_install:
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g codeclimate-test-reporter
  
addons:
    code_climate:
        repo_token: b4dce188163e0eac20b5b617a158755dcf27812e303c722fe050d09b44ae740b

after_script:
  - cat coverage/lcov.info | codeclimate
  
