language: node_js
node_js:
  - "0.10"
cache:
  directories:
    - node_modules

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - mkdir coverage
  - cd server
  - git clone https://github.com/Fluorohydride/ygopro.git
  - ls -p | grep "/"
  - cd ../
  - npm install -g mocha-phantomjs
  - npm install -g mocha
  - npm install -g istanbul
  - npm install -g codeclimate-test-reporter
  
addons:
  code_climate:
    repo_token: 6764db5cccd1a7d62f6acaf5c9316101b683ee711ad3800e4f9a3a115ceacdb1 

after_script:
  - cat coverage/lcov.info | codeclimate
  